
module.exports = {
    entry: './src/main.js',
    outputDir: './dist',
    formats: ['iife', 'esm'],
    minify: true,
    features: {
        polyfills: ['fetch', 'Promise'],
        externalDeps: ['lodash']
    },
    banner: `// Generated by Bookmarklet Factory - ${new Date().toISOString()}\n`
};
